const account_mt5 = [
    { 
        "server" : "Darwinex-Demo", 
        "accountNumber" : 3000015095, 
        "password" : "t7y8Ja8MqyE3",
        "version" : 5, 
    },
    { 
        "server" : "Coinexx-Demo", 
        "accountNumber" : 806090, 
        "password" : "uwA2UJ@862",
        "version" : 5, 
    },
    { 
        "server" : "Just2Trade-MT5", 
        "accountNumber" : 3043055, 
        "password" : "yvqig3ie",
        "version" : 5, 
    },
    { 
        "server" : "FXChoice-MetaTrader 5 Pro", 
        "accountNumber" : 614441, 
        "password" : "MWdjMi4O",
        "version" : 5, 
    },
    { 
        "server" : "Amega-Forex", 
        "accountNumber" : 1000082990, 
        "password" : "QFevL2k1",
        "version" : 5, 
    },
    { 
        "server" : "LiteForexInvestments-MT5.com", 
        "accountNumber" : 36267, 
        "password" : "90hqvJEAN",
        "version" : 5, 
    },
    { 
        "server" : "FxPro-MT5", 
        "accountNumber" :5296338 , 
        "password" : "TbfUERJ5",
        "version" : 5, 
    },

    { 
        "server" : "TickmillUK-DEV", 
        "accountNumber" : 13434, 
        "password" : "dq7edvzo",
        "version" : 5, 
    },
    { 
        "server" : "Alpari-MT5", 
        "accountNumber" : 17039941, 
        "password" : "WI1WO0Gy7",
        "version" : 5, 
    },
    { 
        "server" : "ForexTimeFXTM-Demo01", 
        "accountNumber" : 35368865, 
        "password" : "p4uspfuo",
        "version" : 5, 
    },
    { 
        "server" : "HYCM-Live", 
        "accountNumber" : 8888511991, 
        "password" : "nfato5hp",
        "version" : 5, 
    },
    { 
        "server" : "FIBOGroup-MT5 Server", 
        "accountNumber" : 3002796, 
        "password" : "JIzABUf",
        "version" : 5, 
    },
    { 
        "server" : "HFMarketsGlobal-Demo", 
        "accountNumber" : 48028927, 
        "password" : "s3cciYP^",
        "version" : 5, 
    },
    { 
        "server" : "XMGlobal-MT5", 
        "accountNumber" :25714631 , 
        "password" : "YNBK6m!i!8q8ZQu",
        "version" : 5, 
    },
    { 
        "server" : "LegacyFX-Server", 
        "accountNumber" : 1300293482, 
        "password" : "MoN$t3rAn0N",
        "version" : 5, 
    },
    { 
        "server" : "Exness-MT5Trial", 
        "accountNumber" : 2241847, 
        "password" : "BzLJHn915",
        "version" : 5, 
    },
    { 
        "server" : "AdmiralMarkets-Live", 
        "accountNumber" : 30255968, 
        "password" : "TikTik#90HQV",
        "version" : 5, 
    },
    { 
        "server" : "IronFX-Demo1", 
        "accountNumber" : 500005746, 
        "password" : "l3ibhsjd",
        "version" : 5, 
    },
    { 
        "server" : "Pepperstone-Demo", 
        "accountNumber" : 87778, 
        "password" : "lTh0vkiu",
        "version" : 5, 
    },
    { 
        "server" : "InstaForex-Server ", 
        "accountNumber" :9452124 , 
        "password" : "dk7zycmz",
        "version" : 5, 
    },
    { 
        "server" : "FortFS-Live", 
        "accountNumber" : 1000012347, 
        "password" : "6urfnruq",
        "version" : 5, 
    },
    { 
        "server" : "ICMarketsSC-Demo", 
        "accountNumber" : 50236258, 
        "password" : "JM3eMynu",
        "version" : 5, 
    },
    { 
        "server" : "OctaFX-Demo", 
        "accountNumber" :7086700 , 
        "password" : "9aZYqA6e",
        "version" : 5, 
    },
    { 
        "server" : "FreshForex-MT5", 
        "accountNumber" : 1031187, 
        "password" : "piozxlm2",
        "version" : 5, 
    },
    { 
        "server" : "TeleTRADECY-Sharp ECN", 
        "accountNumber" : 474951, 
        "password" : "AJsrfz8",
        "version" : 5, 
    },
    {
        "server" : "mt5-demo01.pepperstone.com", 
        "accountNumber" : 82871, 
        "password" : "Anhnh7383", 
        "version" : 5, 
    },
    {
        "server" : "XMGlobal-MT5", 
        "accountNumber" : 26128959, 
        "password" : "P@ssword1", 
        "version" : 5, 
    },
    {
        "server" : "FreshForex-MT5", 
        "accountNumber" : 1028798, 
        "password" : "nuPInu6roX", 
        "version" : 5, 
    },
    {
        "server" : "FXChoice-MetaTrader 5 Pro", 
        "accountNumber" : 26573, 
        "password" : "lnVwpC2x", 
        "version" : 5, 
    },
    {
        "server" : "AdmiralMarkets-Demo", 
        "accountNumber" : 40792747, 
        "password" : "wu37BJ6qjIvz", 
        "version" : 5, 
    },
    {
        "server" : "AdmiralMarkets-Demo", 
        "accountNumber" : 40792745, 
        "password" : "721wZf3H0uJC", 
        "version" : 5, 
    },
    {
        "server" : "AdmiralMarkets-Demo", 
        "accountNumber" : 40792742, 
        "password" : "8U3KI4uB9Erh", 
        "version" : 5, 
    },
    {
        "server" : "Pepperstone-Demo", 
        "accountNumber" : 100131, 
        "password" : "3swczgmv", 
        "version" : 5, 
    },
    {
        "server" : "Pepperstone-Demo", 
        "accountNumber" : 100129, 
        "password" : "6lxekhmq", 
        "version" : 5, 
    },
    {
        "server" : "Pepperstone-Demo", 
        "accountNumber" :100127 , 
        "password" : "dhx8xerb", 
        "version" : 5, 
    },
    {
        "server" : "Pepperstone-Demo", 
        "accountNumber" :100126 , 
        "password" : "bgoknt8u", 
        "version" : 5, 
    },
    {
        "server" : "Pepperstone-Demo", 
        "accountNumber" : 100125, 
        "password" : "kx1zsies", 
        "version" : 5, 
    },
    {
        "server" : "Pepperstone-Demo", 
        "accountNumber" :100124 , 
        "password" : "g3ktwjns", 
        "version" : 5, 
    },
    {
        "server" : "Pepperstone-Demo", 
        "accountNumber" : 100122, 
        "password" : "jvwzdw2s", 
        "version" : 5, 
    },
    {
        "server" : "Pepperstone-Demo", 
        "accountNumber" : 100120, 
        "password" : "vaz2zzio", 
        "version" : 5, 
    },
    {
        "server" : "Pepperstone-Demo", 
        "accountNumber" : 100119, 
        "password" : "v4mgybmr", 
        "version" : 5, 
    },
    {
        "server" : "AdmiralMarkets-Demo", 
        "accountNumber" : 40738733, 
        "password" : "IV4a0zY5142F", 
        "version" : 5, 
    },
    // {
    //     "server" : "Pepperstone-Demo", 
    //     "accountNumber" : , 
    //     "password" : "", 
    //     "version" : 5, 
    // },
    // {
    //     "server" : "Pepperstone-Demo", 
    //     "accountNumber" : , 
    //     "password" : "", 
    //     "version" : 5, 
    // },
    // {
    //     "server" : "Pepperstone-Demo", 
    //     "accountNumber" : , 
    //     "password" : "", 
    //     "version" : 5, 
    // },
    // {
    //     "server" : "Pepperstone-Demo", 
    //     "accountNumber" : , 
    //     "password" : "", 
    //     "version" : 5, 
    // },

    // {
    //     "server" : "", 
    //     "accountNumber" : , 
    //     "password" : "", 
    //     "version" : 5, 
    // },
    // {
    //     "server" : "", 
    //     "accountNumber" : , 
    //     "password" : "", 
    //     "version" : 5, 
    // },
    // {
    //     "server" : "", 
    //     "accountNumber" : , 
    //     "password" : "", 
    //     "version" : 5, 
    // },
    // {
    //     "server" : "", 
    //     "accountNumber" : , 
    //     "password" : "", 
    //     "version" : 5, 
    // },
    // {
    //     "server" : "", 
    //     "accountNumber" : , 
    //     "password" : "", 
    //     "version" : 5, 
    // },
    // {
    //     "server" : "", 
    //     "accountNumber" : , 
    //     "password" : "", 
    //     "version" : 5, 
    // }
]

module.exports = {
    account_mt5 
}